server.port=8081

spring.application.name=api-gateway

spring.cloud.gateway.routes[0].id=measurement-service
spring.cloud.gateway.routes[0].uri=lb://measurement-service
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/v1/quantities/**

spring.cloud.gateway.routes[1].id=user-service
spring.cloud.gateway.routes[1].uri=lb://user-service
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/v1/auth/**,/oauth2/**,/login/oauth2/**

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true