spring.application.name=quantity-measurement-app

# ===============================
# H2 DATABASE CONFIGURATION
# ===============================
spring.datasource.url=jdbc:h2:mem:quantitymeasurementdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=


# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# H2 CONSOLE
# ===============================
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=true

# ===============================
# SWAGGER / OPENAPI
# ===============================
springdoc.api-docs.path=/api-docs

# ===============================
# ACTUATOR
# ===============================
management.endpoints.web.exposure.include=*

# ===============================
# LOGGING
# ===============================
logging.level.org.springframework=INFO
logging.level.com.bridgelabz=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# ===============================
# SERVER
# ===============================
server.port=8080

# ===============================
# GOOGLE OAUTH2
# ===============================
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=openid,email,profile

# ===============================
# JWT
# ===============================
jwt.secret=${JWT_SECRET:my-super-secret-jwt-key-my-super-secret-jwt-key-123456789}
jwt.expiration-ms=86400000